### ISSUE TITLE
kolla fler veckor 

### ISSUE THREAD

**Issue by BreezXD** [TRSGuy/Improved-Novaschem#20]
in the original web viewer you were able to check the on coming weeks and see if there were any changes in the schedule in a week or two by that mean you could see every single brake you were gonna get pliz fix XD

**Comment by TRSGuy** [comment]
Hey @BreezXD Thanks for the suggestion man I'll be implementing this in the coming weeks. I'll add you to the patchnotes.

**Comment by TRSGuy** [comment]
This issue is taken care of, I Implemented the suggestion with a `<input type="number">` to select which week should be displayed
